name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run release
    - name: Get build version
      id: get-build-version
      run: echo "::set-output name=build-version::$(node -p "require('./package.json').version")"
      shell: bash
    - name: Tag repo
      uses: mstark5652/tag-repo@v0.2.0
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        build-version: ${{ steps.get-build-version.outputs.build-version }}
        build-message: 'New release'
    - name: Upload to s3
      run: node ./scripts/publishS3.js upload
      env:
        CI: true
        AWS_KEY: ${{ secrets.AWS_KEY }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
